### ISSUE TITLE
Compilation failure of all the classes which are dependent on "Avro generated sources" due to "Avro generated sources" missing in the build path

### ISSUE THREAD

**Issue by ajithprasadanand** [confluentinc/kafka-streams-examples#84] opened 2018-03-16 02:25 UTC

**Comment by ajithprasadanand** [comment] 2018-03-16 02:51
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.10</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/scala</source>
				

> <source>${project.build.directory}/generated-sources</source> missing

                            </sources>
                        </configuration>
                    </execution>

**Comment by mjsax** [comment] 2018-03-16 17:28
@ajithprasadanand Thanks for reporting this issue. It's a little unclear to me what the problem is. What are you trying to do? What is the error (full output) you get? What branch are you referring to?

**Comment by ajithprasadanand** [comment] 2018-03-19 09:41
@mjsax Sorry for the late reply. I am trying to "Maven build/install" the app from within eclipse. The errors are "compilation errors" on all the classes which imports Avro generated sources. I am referring to the Master.

**Comment by mjsax** [comment] 2018-03-19 17:06
Eclipse cannot handle this plugin. However, it should be sufficient to do a `mvn package` on command line a single time to generate the required AVRO class files. Afterwards, Eclipse should be able to pick up those files.

**Comment by ajithprasadanand** [comment] 2018-03-20 04:04
@mjsax  Thanks for your reply. Correct me please if I am wrong.The mvn compiled classes were already present in generated-sources but the IDE was not picking it. I had to add the following line in the pom:
	**<source>${project.build.directory}/generated-sources</source>**


<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.10</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/scala</source>
								<source>${project.build.directory}/generated-sources</source>
                            </sources>
                        </configuration>
                    </execution>

Thanks for your time.

**Comment by mjsax** [comment] 2018-03-20 05:58
I see. Did not look into the details -- just remember from the past that there was an issue like this. If the change fixes the Eclipse setup, it would be great if you could contribute a PR :) Might be best to open a PR against 3.3.0-post branch and we can merge it into all other branches from there.

**Comment by ajithprasadanand** [comment] 2018-03-20 08:49
Will do. Thanks.

**Comment by mjsax** [comment] 2018-03-28 20:44
PR: https://github.com/confluentinc/kafka-streams-examples/pull/99

**Comment by mjsax** [comment] 2018-04-06 18:39
Fixed via #102

**Closed by mjsax** 2018-04-06 18:39 UTC
